### ISSUE TITLE
About Image2Stylegan++

### ISSUE THREAD

**Issue by xuedue** [syguan96/Novel-StyleGAN-Inversion-Papers#1]
Dear author, I have used your previous image2stylegan, it's very useful. And now I am looking forward to your image2stylegan++ code. I wonder if you have any plans to reproduce image2stylegan++ recently.

**Comment by syguan96** [comment]
After careful consideration, I should reclarify my viewpoint. 

Yes, Image2StyleGAN++ can be a baseline in gan inversion. But I won't reimplement it right now since that optimizing both noise and latent code is non-trivial for deep CNN.

**Comment by xuedue** [comment]
Sorry, I don’t quite understand what the "fair baseline" means. For Image Gan Inversion, in order to compare different methods, we can set the same pre-training model and data set for fair comparison. I think this has nothing to do with adding a set of optimizes noises.

**Comment by syguan96** [comment]
For gan inversion, reconstruction ability just one of dimension we should consider. The down-stream tasks such as image editing is more meaningful I think. Optimize noise surely leads to higher reconstruction quality, but it’s harmful to learn W+ code.

发自我的iPhone
